### ISSUE TITLE
Can I Use The Frontend For My App?

### ISSUE THREAD

**Issue by a69y** [dhanushreddy291/Redis-URL-Shortner#5]
I Really Loved The UI Of This, So Can I Use This?

**Comment by dhanushreddy291** [comment]
Yeah Sure Aditya 😀. You can take any part of my code as you like.

**Comment by a69y** [comment]
Thanks!, btw, See appopener.xyz

**Comment by dhanushreddy291** [comment]
Also do checkout a Cloudflare Worker Version, where the Redis Database is replaced by Key Value pairs on Cloudflare edge network:
https://github.com/dhanushreddy291/Tinyme
tinyme.ml

**Comment by a69y** [comment]
:)
